### ISSUE TITLE
unable to compile

### ISSUE THREAD

**Issue by tdhock** [IshmaelBelghazi/gpuClassifieR#1]
on my system nvcc is under /usr/bin

```
thocking@silene:~$ nvcc
nvcc fatal   : No input files specified; use option --help for more information
thocking@silene:~$ which nvcc
/usr/bin/nvcc
thocking@silene:~$ 
```

so I can't compile your code

```
> devtools::install_github("IshmaelBelghazi/gpuClassifieR")
Installing github repo gpuClassifieR/master from IshmaelBelghazi
Downloading master.zip from https://github.com/IshmaelBelghazi/gpuClassifieR/archive/master.zip
Installing package from /tmp/Rtmp7P3p8I/master.zip
arguments 'minimized' and 'invisible' are for Windows only
Installing gpuClassifier
'/home/thocking/lib/R/bin/R' --vanilla CMD build  \
  '/tmp/Rtmp7P3p8I/devtools14d82eb7bf00/gpuClassifieR-master' --no-manual  \
  --no-resave-data 

* checking for file '/tmp/Rtmp7P3p8I/devtools14d82eb7bf00/gpuClassifieR-master/DESCRIPTION' ... OK
* preparing 'gpuClassifier':
* checking DESCRIPTION meta-information ... OK
* cleaning src
* installing the package to build vignettes
      -----------------------------------
* installing *source* package 'gpuClassifier' ...
** libs
** arch - 
/usr/local/cuda/bin/nvcc -gencode arch=compute_20,code=sm_20 -gencode arch=compute_30,code=sm_30, -gencode arch=compute_32,code=sm_32 -gencode arch=compute_35,code=sm_35, -gencode arch=compute_37,code=sm_37, -gencode arch=compute_50,code=sm_50 -c -I. -I"/usr/local/cuda/include" -I"/home/thocking/lib/R/include"  -Xcompiler -fpic entrypoints-model_logreg_cuda.cu -o entrypoints-model_logreg_cuda.o
/bin/bash: /usr/local/cuda/bin/nvcc: No such file or directory
make: *** [entrypoints-model_logreg_cuda.o] Error 127
ERROR: compilation failed for package 'gpuClassifier'
* removing '/tmp/RtmpjaD9KU/Rinst18a441dc07d/gpuClassifier'
      -----------------------------------
ERROR: package installation failed
Error: Command failed (1)
> sessionInfo()
R version 3.1.3 (2015-03-09)
Platform: x86_64-unknown-linux-gnu (64-bit)
Running under: Ubuntu precise (12.04.5 LTS)

locale:
 [1] LC_CTYPE=en_CA.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_CA.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_CA.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] graphics  utils     datasets  grDevices stats     methods   base     

other attached packages:
[1] testthat_0.9.1.9001  PeakSegDP_2015.03.11 RColorBrewer_1.0-5  
[4] lattice_0.20-30      plotly_0.5.25        ggplot2_1.0.0.99    
[7] RJSONIO_1.3-0        RCurl_1.95-4.1       bitops_1.0-6        

loaded via a namespace (and not attached):
 [1] colorspace_1.2-4 compiler_3.1.3   crayon_1.1.0     devtools_1.5    
 [5] dichromat_2.0-0  digest_0.6.4     evaluate_0.5.5   formatR_1.0     
 [9] grid_3.1.3       gtable_0.1.2     httr_0.2         knitr_1.9       
[13] labeling_0.2     MASS_7.3-39      memoise_0.1      munsell_0.4.2   
[17] parallel_3.1.3   plyr_1.8.1       proto_0.3-10     Rcpp_0.11.4     
[21] reshape2_1.2.2   scales_0.2.3     stringr_0.6.2    tools_3.1.3     
[25] whisker_0.3-2   
> 
```

**Comment by IshmaelBelghazi** [comment]
The installation can't find your Cuda directory. Do you have a CUDA_HOME variable in your environment?

**Comment by tdhock** [comment]
nope

```
thocking@silene:~$ echo $CUDA_HOME

thocking@silene:~$ R

R version 3.1.3 (2015-03-09) -- "Smooth Sidewalk"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-unknown-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> Sys.getenv("CUDA_HOME")
[1] ""
> Sys.getenv("HOME")
[1] "/home/thocking"
> devtools::install_github("IshmaelBelghazi/gpuClassifieR")
Installing github repo gpuClassifieR/master from IshmaelBelghazi
Downloading master.zip from https://github.com/IshmaelBelghazi/gpuClassifieR/archive/master.zip
Installing package from /tmp/RtmprBRR45/master.zip
arguments 'minimized' and 'invisible' are for Windows only
Installing gpuClassifieR
'/home/thocking/lib/R/bin/R' --vanilla CMD build  \
  '/tmp/RtmprBRR45/devtools10eb4da42579/gpuClassifieR-master' --no-manual  \
  --no-resave-data 

* checking for file '/tmp/RtmprBRR45/devtools10eb4da42579/gpuClassifieR-master/DESCRIPTION' ... OK
* preparing 'gpuClassifieR':
* checking DESCRIPTION meta-information ... OK
* cleaning src
* installing the package to build vignettes
      -----------------------------------
* installing *source* package 'gpuClassifieR' ...
** libs
** arch - 
/usr/local/cuda/bin/nvcc -gencode arch=compute_20,code=sm_20 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_32,code=sm_32 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -c -I. -I(CUDA_HOME)/include -I/home/thocking/lib/R/include  -Xcompiler -fpic --use_fast_math entrypoints-model_logreg_cuda.cu -o entrypoints-model_logreg_cuda.o
/bin/bash: -c: line 0: syntax error near unexpected token `('
/bin/bash: -c: line 0: `/usr/local/cuda/bin/nvcc -gencode arch=compute_20,code=sm_20 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_32,code=sm_32 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -c -I. -I(CUDA_HOME)/include -I/home/thocking/lib/R/include  -Xcompiler -fpic --use_fast_math entrypoints-model_logreg_cuda.cu -o entrypoints-model_logreg_cuda.o'
make: *** [entrypoints-model_logreg_cuda.o] Error 1
ERROR: compilation failed for package 'gpuClassifieR'
* removing '/tmp/Rtmp5USaU9/Rinst10f534b1edc4/gpuClassifieR'
      -----------------------------------
ERROR: package installation failed
Error: Command failed (1)
> 
```

**Comment by tdhock** [comment]
if I set CUDA_HOME I still get an error

```
thocking@silene:~$ CUDA_HOME=/usr R

R version 3.1.3 (2015-03-09) -- "Smooth Sidewalk"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-unknown-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> devtools::install_github("IshmaelBelghazi/gpuClassifieR")
Installing github repo gpuClassifieR/master from IshmaelBelghazi
Downloading master.zip from https://github.com/IshmaelBelghazi/gpuClassifieR/archive/master.zip
Installing package from /tmp/Rtmps9mX20/master.zip
arguments 'minimized' and 'invisible' are for Windows only
Installing gpuClassifieR
'/home/thocking/lib/R/bin/R' --vanilla CMD build  \
  '/tmp/Rtmps9mX20/devtools115e5a01b937/gpuClassifieR-master' --no-manual  \
  --no-resave-data 

* checking for file '/tmp/Rtmps9mX20/devtools115e5a01b937/gpuClassifieR-master/DESCRIPTION' ... OK
* preparing 'gpuClassifieR':
* checking DESCRIPTION meta-information ... OK
* cleaning src
* installing the package to build vignettes
      -----------------------------------
* installing *source* package 'gpuClassifieR' ...
** libs
** arch - 
/usr/bin/nvcc -gencode arch=compute_20,code=sm_20 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_32,code=sm_32 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -c -I. -I(CUDA_HOME)/include -I/home/thocking/lib/R/include  -Xcompiler -fpic --use_fast_math entrypoints-model_logreg_cuda.cu -o entrypoints-model_logreg_cuda.o
/bin/bash: -c: line 0: syntax error near unexpected token `('
/bin/bash: -c: line 0: `/usr/bin/nvcc -gencode arch=compute_20,code=sm_20 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_32,code=sm_32 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -c -I. -I(CUDA_HOME)/include -I/home/thocking/lib/R/include  -Xcompiler -fpic --use_fast_math entrypoints-model_logreg_cuda.cu -o entrypoints-model_logreg_cuda.o'
make: *** [entrypoints-model_logreg_cuda.o] Error 1
ERROR: compilation failed for package 'gpuClassifieR'
* removing '/tmp/Rtmp3d4m45/Rinst116745f2fe3f/gpuClassifieR'
      -----------------------------------
ERROR: package installation failed
Error: Command failed (1)
> Sys.getenv("CUDA_HOME")
[1] "/usr"
> 
```

**Comment by IshmaelBelghazi** [comment]
You need to have a rather recent version of the cuda toolkit. After that,  setting  the CUDA_HOME environment variable to the root of the toolkit installation directory should make it work. For instance if you installed the CUDA toolkit in /usr/local/cuda-6.5 (which is the default installation directory) then you should export CUDA_HOME=/usr/local/cuda-6.5

**Comment by tdhock** [comment]
Is my nvcc too old? This is the default version of nvcc on my ubuntu precise system.

```
thocking@silene:~$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2011 NVIDIA Corporation
Built on Thu_May_12_11:09:45_PDT_2011
Cuda compilation tools, release 4.0, V0.2.1221
```

**Comment by IshmaelBelghazi** [comment]
I think it might be.  here is mine

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2014 NVIDIA Corporation
Built on Thu_Jul_17_21:41:27_CDT_2014
Cuda compilation tools, release 6.5, V6.5.12
```

Moreover the package those build on travis (it runs precise x64).

```
Building with: R CMD build 
0.51s$ R CMD build --no-build-vignettes --no-manual .
* checking for file ‘./DESCRIPTION’ ... OK
* preparing ‘gpuClassifieR’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* checking for LF line-endings in source and make files
* checking for empty or unneeded directories
* looking to see if a ‘data/datalist’ file should be added
* building ‘gpuClassifieR_0.1.3.tar.gz’

```

Here is how I setup the environment on travis. Please keep in my mind that I only install what is strictly necessary to build in the cuda toolkit. You might want to install everything and also update your gpu drivers.

``` bash
CUDA_URL=http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1204/x86_64/cuda-repo-ubuntu1204_6.5-14_amd64.deb
CUDA_FILE=/tmp/cuda_install.deb
curl $CUDA_URL -o $CUDA_FILE
dpkg -i $CUDA_FILE
rm -f $CUDA_FILE
apt-get -y update
apt-get -y install cuda-core-6-5 cuda-cublas-6-5 cuda-cublas-dev-6-5 cuda-cudart-6-5 cuda-cudart-dev-6-5 cuda-curand-6-5 cuda-curand-dev-6-5
ln -s /usr/local/cuda-6.5 /usr/local/cuda
```

**Comment by tdhock** [comment]
same problem even with the cuda-6.5 you suggested

```
thocking@silene:~/R$ CUDA_HOME=/usr/local/cuda-6.5 R CMD INSTALL gpuClassifieR/
* installing to library ‘/home/thocking/lib/R/library’
* installing *source* package ‘gpuClassifieR’ ...
** libs
** arch - 
/usr/local/cuda-6.5/bin/nvcc -gencode arch=compute_20,code=sm_20 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_32,code=sm_32 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -c -I. -I(CUDA_HOME)/include -I/home/thocking/lib/R/include  -Xcompiler -fpic --use_fast_math entrypoints-model_logreg_cuda.cu -o entrypoints-model_logreg_cuda.o
/bin/bash: -c: line 0: syntax error near unexpected token `('
/bin/bash: -c: line 0: `/usr/local/cuda-6.5/bin/nvcc -gencode arch=compute_20,code=sm_20 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_32,code=sm_32 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -c -I. -I(CUDA_HOME)/include -I/home/thocking/lib/R/include  -Xcompiler -fpic --use_fast_math entrypoints-model_logreg_cuda.cu -o entrypoints-model_logreg_cuda.o'
make: *** [entrypoints-model_logreg_cuda.o] Error 1
ERROR: compilation failed for package ‘gpuClassifieR’
* removing ‘/home/thocking/lib/R/library/gpuClassifieR’
thocking@silene:~/R$ CUDA_HOME=/usr/local/cuda-6.5 R CMD build gpuClassifieR/
* checking for file ‘gpuClassifieR/DESCRIPTION’ ... OK
* preparing ‘gpuClassifieR’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* installing the package to build vignettes
      -----------------------------------
* installing *source* package ‘gpuClassifieR’ ...
** libs
** arch - 
/usr/local/cuda-6.5/bin/nvcc -gencode arch=compute_20,code=sm_20 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_32,code=sm_32 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -c -I. -I(CUDA_HOME)/include -I/home/thocking/lib/R/include  -Xcompiler -fpic --use_fast_math entrypoints-model_logreg_cuda.cu -o entrypoints-model_logreg_cuda.o
/bin/bash: -c: line 0: syntax error near unexpected token `('
/bin/bash: -c: line 0: `/usr/local/cuda-6.5/bin/nvcc -gencode arch=compute_20,code=sm_20 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_32,code=sm_32 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -c -I. -I(CUDA_HOME)/include -I/home/thocking/lib/R/include  -Xcompiler -fpic --use_fast_math entrypoints-model_logreg_cuda.cu -o entrypoints-model_logreg_cuda.o'
make: *** [entrypoints-model_logreg_cuda.o] Error 1
ERROR: compilation failed for package ‘gpuClassifieR’
* removing ‘/tmp/RtmpNhPyXW/Rinst1650d8b02a4/gpuClassifieR’
      -----------------------------------
ERROR: package installation failed
thocking@silene:~/R$ 
```

**Comment by IshmaelBelghazi** [comment]
This one is on my end. I was missing a $ somewhere. I did not come up on my machine or on travis bacause I had already defined the CUDA_INCLUDE variable. I think it should work now.

**Comment by tdhock** [comment]
making progress but still an error. R.h does exist but the `-I/home/thocking/lib/R/include` flag is not passed to nvcc.

```
> devtools::install_github("IshmaelBelghazi/gpuClassifieR")
Installing github repo gpuClassifieR/master from IshmaelBelghazi
Downloading master.zip from https://github.com/IshmaelBelghazi/gpuClassifieR/archive/master.zip
Installing package from /tmp/RtmpXNFbSR/master.zip
arguments 'minimized' and 'invisible' are for Windows only
Installing gpuClassifieR
'/home/thocking/lib/R/bin/R' --vanilla CMD INSTALL  \
  '/tmp/RtmpXNFbSR/devtools173b670a460e/gpuClassifieR-master'  \
  --library='/home/thocking/lib/R/library' --install-tests 

* installing *source* package 'gpuClassifieR' ...
** libs
** arch - 
/usr/local/cuda/bin/nvcc -gencode arch=compute_20,code=sm_20 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_32,code=sm_32 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -c -I. -I/usr/local/cuda/include -I/home/thocking/lib/R/include  -Xcompiler -fpic --use_fast_math entrypoints-model_logreg_cuda.cu -o entrypoints-model_logreg_cuda.o
/usr/local/cuda/bin/nvcc -gencode arch=compute_20,code=sm_20 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_32,code=sm_32 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -c -I. -I/usr/local/cuda/include -I/home/thocking/lib/R/include  -Xcompiler -fpic --use_fast_math entrypoints-trainer_gd_cuda.cu -o entrypoints-trainer_gd_cuda.o
/usr/local/cuda/bin/nvcc -gencode arch=compute_20,code=sm_20 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_32,code=sm_32 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -c -I. -I/usr/local/cuda/include -I/home/thocking/lib/R/include  -Xcompiler -fpic --use_fast_math model_logreg_cuda.cu -o model_logreg_cuda.o
/usr/local/cuda/bin/nvcc --compiler-options -std=gnu99 -c   -Xcompiler -fpic --use_fast_math cost-functions_C.c -o cost-functions_C.o
cost-functions_C.c:1:15: fatal error: R.h: No such file or directory
compilation terminated.
make: *** [cost-functions_C.o] Error 1
ERROR: compilation failed for package 'gpuClassifieR'
* removing '/home/thocking/lib/R/library/gpuClassifieR'
Error: Command failed (1)
> dir("/home/thocking/lib/R/include")
 [1] "R_ext"        "R.h"          "Rconfig.h"    "Rdefines.h"   "Rembedded.h" 
 [6] "Rinterface.h" "Rinternals.h" "Rmath.h"      "Rversion.h"   "S.h"         
> 
```

**Comment by tdhock** [comment]
acutally the -I is passed for the first 3 nvcc calls but not the last one which results in an error. any ideas?

**Comment by IshmaelBelghazi** [comment]
Same type of error. I had R_INCLUDE defined in my environment and it hid a spelling mistake. I just fixed it, unset all my environment vars. It should work now. I think that the files are also in the include path on travis.

**Comment by tdhock** [comment]
one more error, probably because you have LD_LIBRARY_PATH defined?

```
thocking@silene:~/R$ CUDA_HOME=/usr/local/cuda-6.5 R CMD build gpuClassifieR
* checking for file ‘gpuClassifieR/DESCRIPTION’ ... OK
* preparing ‘gpuClassifieR’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* checking for LF line-endings in source and make files
* checking for empty or unneeded directories
* looking to see if a ‘data/datalist’ file should be added
* building ‘gpuClassifieR_0.1.3.tar.gz’
Warning: invalid uid value replaced by that for user 'nobody'

thocking@silene:~/R$ CUDA_HOME=/usr/local/cuda-6.5 R CMD INSTALL gpuClassifieR
* installing to library ‘/home/thocking/lib/R/library’
* installing *source* package ‘gpuClassifieR’ ...
** libs
** arch - 
/usr/local/cuda-6.5/bin/nvcc -gencode arch=compute_20,code=sm_20 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_32,code=sm_32 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -c -I. -I/usr/local/cuda-6.5/include -I/home/thocking/lib/R/include  -Xcompiler -fpic --use_fast_math entrypoints-model_logreg_cuda.cu -o entrypoints-model_logreg_cuda.o
/usr/local/cuda-6.5/bin/nvcc -gencode arch=compute_20,code=sm_20 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_32,code=sm_32 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -c -I. -I/usr/local/cuda-6.5/include -I/home/thocking/lib/R/include  -Xcompiler -fpic --use_fast_math entrypoints-trainer_gd_cuda.cu -o entrypoints-trainer_gd_cuda.o
/usr/local/cuda-6.5/bin/nvcc -gencode arch=compute_20,code=sm_20 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_32,code=sm_32 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -c -I. -I/usr/local/cuda-6.5/include -I/home/thocking/lib/R/include  -Xcompiler -fpic --use_fast_math model_logreg_cuda.cu -o model_logreg_cuda.o
/usr/local/cuda-6.5/bin/nvcc --compiler-options -std=gnu99 -c -I. -I/home/thocking/lib/R/include -Xcompiler -fpic -O3 cost-functions_C.c -o cost-functions_C.o
/usr/local/cuda-6.5/bin/nvcc --compiler-options -std=gnu99 -c -I. -I/home/thocking/lib/R/include -Xcompiler -fpic -O3 cudaLogReg-init.c -o cudaLogReg-init.o
/usr/local/cuda-6.5/bin/nvcc --compiler-options -std=gnu99 -c -I. -I/home/thocking/lib/R/include -Xcompiler -fpic -O3 cudaLogReg-utils.c -o cudaLogReg-utils.o
/usr/local/cuda-6.5/bin/nvcc --compiler-options -std=gnu99 -c -I. -I/home/thocking/lib/R/include -Xcompiler -fpic -O3 entrypoints-model_logreg_C.c -o entrypoints-model_logreg_C.o
/usr/local/cuda-6.5/bin/nvcc --compiler-options -std=gnu99 -c -I. -I/home/thocking/lib/R/include -Xcompiler -fpic -O3 entrypoints-trainer_gd_C.c -o entrypoints-trainer_gd_C.o
/usr/local/cuda-6.5/bin/nvcc --compiler-options -std=gnu99 -c -I. -I/home/thocking/lib/R/include -Xcompiler -fpic -O3 model_logreg_C.c -o model_logreg_C.o
/usr/local/cuda-6.5/bin/nvcc -gencode arch=compute_20,code=sm_20 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_32,code=sm_32 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -shared  -Xlinker   -L/home/thocking/lib/R/lib -L/usr/local/cuda-6.5/lib64 -lcublas -L/home/thocking/lib/R/lib -lRblas ./entrypoints-model_logreg_cuda.o ./entrypoints-trainer_gd_cuda.o ./model_logreg_cuda.o ./cost-functions_C.o ./cudaLogReg-init.o ./cudaLogReg-utils.o ./entrypoints-model_logreg_C.o ./entrypoints-trainer_gd_C.o ./model_logreg_C.o -o gpuClassifieR.so
installing to /home/thocking/lib/R/library/gpuClassifieR/libs
** R
** data
*** moving datasets to lazyload DB
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/thocking/lib/R/library/gpuClassifieR/libs/gpuClassifieR.so':
  libcublas.so.6.5: cannot open shared object file: No such file or directory
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/thocking/lib/R/library/gpuClassifieR’
thocking@silene:~/R$ 
```

**Comment by tdhock** [comment]
it works for me only when I define LD_LIBRARY_PATH.

overall I think this installation process has been much more work than you can expect from the average (or even advanced) useRs, so I would suggest to avoid cuda code in the future if at all possible.

```
thocking@silene:~/R$ CUDA_HOME=/usr/local/cuda-6.5 LD_LIBRARY_PATH=/usr/local/cuda-6.5/lib64 R CMD build gpuClassifieR
* checking for file ‘gpuClassifieR/DESCRIPTION’ ... OK
* preparing ‘gpuClassifieR’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* checking for LF line-endings in source and make files
* checking for empty or unneeded directories
* looking to see if a ‘data/datalist’ file should be added
* building ‘gpuClassifieR_0.1.3.tar.gz’
Warning: invalid uid value replaced by that for user 'nobody'

thocking@silene:~/R$ CUDA_HOME=/usr/local/cuda-6.5 LD_LIBRARY_PATH=/usr/local/cuda-6.5/lib64 R CMD INSTALL gpuClassifieR
* installing to library ‘/home/thocking/lib/R/library’
* installing *source* package ‘gpuClassifieR’ ...
** libs
** arch - 
make: Nothing to be done for `all'.
installing to /home/thocking/lib/R/library/gpuClassifieR/libs
** R
** data
*** moving datasets to lazyload DB
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (gpuClassifieR)
thocking@silene:~/R$ CUDA_HOME=/usr/local/cuda-6.5 R CMD INSTALL gpuClassifieR
* installing to library ‘/home/thocking/lib/R/library’
* installing *source* package ‘gpuClassifieR’ ...
** libs
** arch - 
make: Nothing to be done for `all'.
installing to /home/thocking/lib/R/library/gpuClassifieR/libs
** R
** data
*** moving datasets to lazyload DB
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/thocking/lib/R/library/gpuClassifieR/libs/gpuClassifieR.so':
  libcublas.so.6.5: cannot open shared object file: No such file or directory
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/thocking/lib/R/library/gpuClassifieR’
* restoring previous ‘/home/thocking/lib/R/library/gpuClassifieR’
thocking@silene:~/R$ 
```

**Comment by IshmaelBelghazi** [comment]
Yes I agree. Until I find I process that would make this seamless, I have to agree with you.

**Comment by IshmaelBelghazi** [comment]
BTW I have added a C only branch. The installation process should be problem free.

**Comment by IshmaelBelghazi** [comment]
I will mark the issues as closed since the use of shared libraries requires a properly set LD_LIBRARY_PATH
